### ISSUE TITLE
Converted Levels fail to import to Quaver

### ISSUE THREAD

**Issue by sebimon3** [vysiondev/bmtranslator#1]
This is my first time writing an issue on GitHub, so I'm sorry if I leave out any important details and I apologize in advance for any horrible formatting.

OS: Windows 10 with JP locale
bmtranslator 0.2.0 used from an elevated command prompt

Converting BMS levels to .qp files seems to work just fine, here is the verbose output from bmtranslator:
![cmd_CSSu1kIh6B](https://user-images.githubusercontent.com/77461506/139601126-e639a8c1-6497-4a79-8b30-0e2ce43b7e8b.png)

Looking inside the generated .qp files with 7zip, the structure looks correct. Quaver also extracts them just fine, both drag and drop and opening the file directly with Quaver work and make the corresponding folder appear in the Songs directory. 
However Quaver does not seem to see the map/mapset after importing it. Sometimes, a notification appears saying that importing the song failed, however this only happens about 10% of the time and is very inconsistent.
Using bmtranslator to convert to an .osz file, which Quaver also supports, nets the same result. I do not have osu! installed, so I have not tested wether osu! can import the converted levels correctly.

To see whether this is just a coincidence, i used bmtranslator to convert around 480 songs from BOFXVI and none of them successfully imported. 

I sadly do not know enough about .bms or .qua files to judge whether bmtranslator converted them successfully or not, however I will attach the .bms and .qua files for the same difficulty of a converted song for people to look at:
.bms: https://pastebin.com/rizJ9dXu
.qua: https://pastebin.com/34qXYQV8

Either I am doing something horribly wrong, or bmtranslator is borked for some reason.

**Comment by vysiondev** [comment]
I've looked into this and it appears that it's a YAML syntax error. I tried importing the same BMS map converted to .qua into the game, and the game's runtime.log gave me the following message: `YamlDotNet.Core.SyntaxErrorException: (Line: 8, Col: 1, Idx: 125) - (Line: 8, Col: 1, Idx: 125): While scanning a simple key, could not find expected ':'.`. So in other words, `HasScratchKey:True` has a typo (there should be a space after the colon), which is my mistake. I will fix this as soon as i get the chance.

**Comment by sebimon3** [comment]
Seems like its as easy as adding a space in:
https://github.com/vysiondev/bmtranslator/blob/57b882392174940e452db45c230d63be31dd74ea/convert_to_quaver.go#L35

To:
`	_ = WriteLine(quaFile, fmt.Sprintf("HasScratchKey: %s", scratchKey))`

Tested this just now and Quaver imported it without any problems and the result played just fine.

**Comment by vysiondev** [comment]
This has now been fixed in the latest release. If the problem still isn't fixed please don't hesitate to comment again.
